package akka.ui

trait Listener

case object abort extends Listener
case object activate extends Listener
case object addstream extends Listener
case object addtrack extends Listener
case object afterprint extends Listener
case object beforeactivate extends Listener
case object beforecopy extends Listener
case object beforecut extends Listener
case object beforedeactivate extends Listener
case object beforepaste extends Listener
case object beforeprint extends Listener
case object beforeunload extends Listener
case object blocked extends Listener
case object blur extends Listener
case object bounce extends Listener
case object cached extends Listener
case object canplay extends Listener
case object canplaythrough extends Listener
case object change extends Listener
case object checking extends Listener
case object click extends Listener
case object close extends Listener
case object complete extends Listener
case object connect extends Listener
case object contextmenu extends Listener
case object controllerchange extends Listener
case object copy extends Listener
case object cuechange extends Listener
case object cut extends Listener
case object datachannel extends Listener
case object dblclick extends Listener
case object deactivate extends Listener
case object devicechange extends Listener
case object downloading extends Listener
case object drag extends Listener
case object dragend extends Listener
case object dragenter extends Listener
case object dragleave extends Listener
case object dragover extends Listener
case object dragstart extends Listener
case object drop extends Listener
case object durationchange extends Listener
case object emptied extends Listener
case object ended extends Listener
case object enter extends Listener
case object error extends Listener
case object exit extends Listener
case object fetch extends Listener
case object finish extends Listener
case object focus extends Listener
case object focusin extends Listener
case object focusout extends Listener
case object hashchange extends Listener
case object help extends Listener
case object icecandidate extends Listener
case object iceconnectionstatechange extends Listener
case object identityresult extends Listener
case object idpassertionerror extends Listener
case object idpvalidationerror extends Listener
case object input extends Listener
case object install extends Listener
case object keydown extends Listener
case object keypress extends Listener
case object keyup extends Listener
case object languagechange extends Listener
case object load extends Listener
case object loadeddata extends Listener
case object loadedmetadata extends Listener
case object loadend extends Listener
case object loadstart extends Listener
case object message extends Listener
case object mousedown extends Listener
case object mouseenter extends Listener
case object mouseleave extends Listener
case object mousemove extends Listener
case object mouseout extends Listener
case object mouseover extends Listener
case object mouseup extends Listener
case object mousewheel extends Listener
case object mute extends Listener
case object negotiationneeded extends Listener
case object noupdate extends Listener
case object obsolete extends Listener
case object offline extends Listener
case object online extends Listener
case object open extends Listener
case object overconstrained extends Listener
case object paste extends Listener
case object pause extends Listener
case object peeridentity extends Listener
case object play extends Listener
case object playing extends Listener
case object popstate extends Listener
case object progress extends Listener
case object ratechange extends Listener
case object readystatechange extends Listener
case object removestream extends Listener
case object removetrack extends Listener
case object reset extends Listener
case object resize extends Listener
case object scroll extends Listener
case object seeked extends Listener
case object seeking extends Listener
case object select extends Listener
case object selectionchange extends Listener
case object selectstart extends Listener
case object signalingstatechange extends Listener
case object stalled extends Listener
case object start extends Listener
case object started extends Listener
case object statechange extends Listener
case object stop extends Listener
case object storage extends Listener
case object storagecommit extends Listener
case object submit extends Listener
case object success extends Listener
case object suspend extends Listener
case object timeout extends Listener
case object timeupdate extends Listener
case object unload extends Listener
case object unmute extends Listener
case object updatefound extends Listener
case object updateready extends Listener
case object upgradeneeded extends Listener
case object volumechange extends Listener
case object waiting extends Listener
case object zoom extends Listener
